Update minimum pytest version from 6.2.1 to 6.2.5
Fixes the error

    TypeError: required field "lineno" missing from alias

See: https://stackoverflow.com/a/69569206/118608